#!/usr/bin/perl

use strict;
use Math::BigRat only => 'GMP';
use Math::BigInt only => 'GMP';

my $threshold = Math::BigInt->new('1000000000000');

my $current = Math::BigRat->new(1,1)->bdiv(2);
my $one_half = $current->copy();

# Need that 2n(n-1)+1 is an odd square, say = m^2.
# Inspection of the early results shows that valid values for m
# are generated by the odd numerators of the convergents of the continued
# fraction expansion for sqrt(2)-1:
#
# 1/2, 2/5, 5/12, 12/29, 29/70, 70/169, 169/...
#
# Then p = (m+1)/2 and n can be found by solving the quadratic equation
# relating it to p:

while(1) {
	my $p = $current->numerator()->badd(1)->bdiv(2);
	my $n = $p->copy()->bsub(1)->bmul($p)->bmul(8)->badd(1)->bsqrt()->badd(1)->bdiv(2);

	printf("%s %s %s\n", $current->bstr(), $p->bstr(), $n->bstr());

	if ($threshold->bcmp($n) < 0) {
		printf("%s\n", $p->bstr());
		last;
	}
	
	# do two steps...
	$current = Math::BigRat->new(1,1)->bdiv($current->bmul(4)->badd(10))
		->bsub($one_half)->bneg();
}
